### PR TITLE
Update to build with Gradle 3 and Android Things DP6

### PR DESCRIPTION
**Pull request by joerick**
Hey cagdasc

We've been using this library in a project - thanks for sharing it, it's been really useful.

We had to make a few changes to make it work in our project - those are included in this PR. We've tested it as a Jitpack dependency.

Thanks
Joe

p.s. we've another PR incoming with a bugfix around multi-byte reads.

### CODE REVIEW

**Comment by cagdasc** [comment]
Hello @joerick ,
Why did you implement "maven-gradle-plugin"?

**Comment by joerick** [comment]
Hmm, to be honest, I can't remember! @michaelcolville do you recall?

**Comment by michaelcolville** [comment]
I must have put that in by mistake, I've since removed it on our fork when I did the DP8 upgrade https://github.com/nordprojects/AndroidThings-ADXL345/commit/78fa5b9e7a32c0628d85cc27c20ae21d19a27a92 
@cagdasc shall I do a new pull request that includes the DP8 upgrade?

**Comment by cagdasc** [comment]
@michaelcolville please you can do new pull request.

**Pull request merged**
